version: 2

sources:
  - name: raw
    database: AIRBNB_DE
    schema: RAW
    config:
      loaded_at_field: _loaded_at
      freshness:
        warn_after: {count: 2, period: hour}
        error_after: {count: 8, period: hour}
    tables:
      - name: raw_hosts
      - name: raw_listings
      - name: raw_guests
      - name: raw_bookings
      - name: raw_reviews
      - name: raw_availability_calendar
      - name: raw_listing_events
